### ISSUE TITLE
Failed to run the mongodb MongoDBSampleService.dbs example on a fresh wso2ei !

### ISSUE THREAD

**Issue by atifhub** [wso2/product-ei#1961]
**Description:**

I have an exception while trying tto run the mongodb example MongoDBSampleService.dbs : 

[2018-03-09 15:50:24,604] [EI-Core] ERROR - DBDeployer The MongoDBSampleService.dbs service, which is not valid, caused {1}
**java.lang.NoSuchMethodError**: com.fasterxml.jackson.databind.DeserializationConfig.with(Lcom/fasterxml/jackson/databind/AnnotationIntrospector;)Lcom/fasterxml/jackson/databind/DeserializationConfig;
        at org.jongo.marshall.jackson.configuration.AnnotationModifier.modify(AnnotationModifier.java:33)
        at org.jongo.marshall.jackson.configuration.AbstractMappingBuilder.createMapping(AbstractMappingBuilder.java:56)

 
**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
6.1.1-update23
**OS, DB, other environment details and versions:**    
OS : Debian 9
JAVA VERSION : 1.8.0_162
**Steps to reproduce:**
1 - download https://github.com/wso2/product-ei/releases/download/v6.1.1-update23/wso2ei-6.1.1-update23.zip
2 - go to Data Service -> Upload -> locate the MongoDBSampleService.dbs and upload it
3 - wait a moment the deployment process to finish
4 - List Services and you will see that the new deployed data service is faulty

**Related Issues:**

**Comment by madhawa-gunasekara** [comment]
Thanks for reporting this issue, We will fix this in next week release

**Comment by Nirothipan** [comment]
Hi @atifhub 

Could you please let us know the MongoDB server version you are using to test this sample?

Thanks

**Comment by atifhub** [comment]
Hi,

mongod --version
db version **v3.2.11**
git version: 009580ad490190ba33d1c6253ebd8d91808923e4
OpenSSL version: OpenSSL 1.0.2l  25 May 2017

------

By the way The MongoDBSampleService.dbs sample is working well with this version of wso2ei : 6.1.1-update8
But it fails with wso2ei-6.1.1-update23 and also with wso2ei-6.1.1-update22

**Comment by Nirothipan** [comment]
Hi @atifhub ,

We have fixed this issue. Fix will be available with next release.
Thank you for reporting this.

Regards.

**Comment by atifhub** [comment]
Hi @Nirothipan ,

Thank you ! Shall i know what was done to correct it please ?

Best regards

**Comment by Nirothipan** [comment]
Hi @atifhub ,

There were some version conflicts related to "com.fasterxml.jackson.databind" bundle in the pack which has caused the issue. 

Reagrds
